### ISSUE TITLE
No audio when hosting

### ISSUE THREAD

**Issue by mocsny** [moonlight-stream/moonlight-chrome#83] opened 2016-08-04 19:52 UTC
When I'm hosting, I have no access to options (not sure if intended or not). They way i'm using moonlight chrome is port forwarding then having my friend connect to me through the moonlight app through chrome. We are able to play games together, but only my friend has audio. Is there a fix for this? The game we're playing is Overcooked

**Comment by raidancampbell** [comment] 2016-08-04 20:32
Duplicate of #60 

There is a fix coming in an upcoming release. An unsupported, preliminary, still in-progress preview can be found [here](https://dl.dropboxusercontent.com/u/9034340/moonlight-chrome-7-24-audio-test.crx)

**Closed by raidancampbell** 2016-08-04 20:32 UTC
