### ISSUE TITLE
No video on OSX 10.11.5, Chrome 50.0.2661.102 (64-bit)

### ISSUE THREAD

**Issue by Blunderbuss** [moonlight-stream/moonlight-chrome#59] opened 2016-05-30 01:26 UTC
I can make the connection to the PS4, since I have been able to test this on my home network and can see that the button presses I'm making are having an effect, but I get no video at all coming to the Macbook Pro.

**Comment by cgutman** [comment] 2016-05-30 06:22
Can you add more details about your system? It's working on an Early 2016 MacBook and a Mid 2010 MacBook Pro.

**Comment by Blunderbuss** [comment] 2016-05-30 11:30
MacBook Pro (15-inch, Mid 2010)

2.66 GHz Intel Core i7

8 GB 1067 MHz DDR3

NVIDIA GeForce GT 330M 512 MB

Serial: W8039XXXXXX

Chrome is not in developer mode, if that matters...

Extensions installed: Hoverhound, Lastpass, Lazarus, Moonlight (version
0.3), Slickdeals, Tampermonkey, Camelizer, Zotero

**Comment by cgutman** [comment] 2016-06-09 18:27
This _should_ be fixed by 1f3f4bd0aa6075759673df70975ce2722def4f62 but understanding why the hardware decoder doesn't work in the first place would be nice.

**Comment by cgutman** [comment] 2016-06-14 00:34
Please retest on the v0.4 release please.

**Comment by Blunderbuss** [comment] 2016-06-14 01:05
Hey, sorry - been busy! The video now shows, though hardware decoding
failed for The Witcher 3. It also doesn't work if the video output of the
game is set to go to monitor 2 instead of 1, but I'm not sure if that's a
generic limitation on nvidia's side, or what.

**Comment by cgutman** [comment] 2016-06-14 02:38
Well at least it works at all now. I wonder if it could be a problem with switchable graphics on your MacBook Pro. Do you have any programs installed to manually switch the GPU on your machine? The only time I saw this was when I was playing with Quartz Debug to force the browser to run on the other GPU.

**Comment by Blunderbuss** [comment] 2016-06-14 03:42
I do indeed have gfxcardstatus v2.3 running, but it was set to dynamic
switching, so it shouldn't interfere. I tried it again with the program
closed, but same issue - no hardware decoding with Witcher 3.

**Comment by raidancampbell** [comment] 2016-08-27 15:01
Closed due to inactivity and inability to reproduce

**Closed by raidancampbell** 2016-08-27 15:01 UTC
