### ISSUE TITLE
Duplicate Game Posters

### ISSUE THREAD

**Issue by ShadowBullet** [moonlight-stream/moonlight-chrome#78] opened 2016-07-25 21:48 UTC
When loading up the app it populated the game posters but it duplicated most (not all) of them. I am using the most recent build by @raidancampbell as he pre compiled it. Happy to provide screenshots and whatever else. EDIT: Refreshing the list fixes it (this was a new pairing) so it must only happen on the first initial pair.

**Comment by raidancampbell** [comment] 2016-07-25 21:56
would you mind following the steps [here](http://stackoverflow.com/a/12714052/3006365) to enable inspection of packaged apps?

Follow the steps as you normally do to reproduce the issue, then right click -> `inspect` to bring up the DevTools console.  Navigate to the `Console` tab, select all the text, and email it to me at `aidan@moonlight-stream.com`

**Comment by ShadowBullet** [comment] 2016-07-25 22:07
Odd, I did not do it this time, repeated all the same steps, wonder if was just a one off?

**Comment by ShadowBullet** [comment] 2016-07-25 22:07
This time it repopulated normally as it should. Deleted the app and did the whole process, wish I could reproduce it.

**Comment by raidancampbell** [comment] 2016-07-25 22:09
hmmm, I'd suspect it may exist as a bug on first connection to the server, but it's odd that you couldn't replicate it from deleting the app.  I'll leave this open for a couple weeks, if nobody else sees this behavior I'll close it then

**Comment by ShadowBullet** [comment] 2016-07-25 22:10
BTW, semi-unrelated but I am loving the interface and posters (perhaps the posters should also be a bit closer) anyway it's coming along well. Back to the topic, on the initial try it was populating then duplicated some (Steam, counter strike, Doom) and then didn't duplicate others (black ops 3, far cry 4, etc)

**Comment by ShadowBullet** [comment] 2016-07-25 22:10
All right sounds good

**Comment by raidancampbell** [comment] 2016-08-08 16:48
Unable to reproduce, no further reports

**Comment by raidancampbell** [comment] 2016-08-27 03:46
Reproduced by rapidly clicking the host before it successfully enters the box art selection (i.e. double clicking a host)

**Closed** 2016-08-27 13:05 UTC
