### ISSUE TITLE
Controller issues with Star Wars Battlefront on macOS client

### ISSUE THREAD

**Issue by bunchjesse** [moonlight-stream/moonlight-chrome#87] opened 2016-08-13 22:11 UTC
I plugged in a controller to play Star Wars Battlefront today and noticed the following issues:

- Using the Chrome client, the character would just stare upward as if the right stick was full aft. There was nothing I could do to fix that. This did not happen using the latest Java client.

- Using the Java client, the controller seemed to work but I lost control of the mouse and keyboard when in-game. I'm not sure how to describe it but it seemed as if some keys were stuck down (but they obviously weren't).

- After giving up on the controller idea, I disconnected the controller from my Mac and re-launched both moonlight (chrome) and the game. The game still thinks that a controller is connected and my mouse and keyboard still do not work properly in-game. The only way to fix this was to restart the Windows computer. It seems like maybe GFE got into some weird state?

Controller: SteelSeries Nimbus connected via USB
OS: macOS Sierra Beta (latest) (Client), Windows 10 Pro (Server)
Hardware: MacBook Pro 15"

**Comment by bunchjesse** [comment] 2016-08-13 22:13
I think that #84 might be another instance of my controller issues but I'm not quite sure.

**Comment by raidancampbell** [comment] 2016-08-27 22:20
Duplicate of #84

**Closed by raidancampbell** 2016-08-27 22:20 UTC

**Comment by bunchjesse** [comment] 2016-08-28 03:06
Hey @raidancampbell, I see how the third issue I raised could be a dupe of #84, however what about the first and second? Those seem like bugs rather than expected behavior of GFE.

**Comment by raidancampbell** [comment] 2016-08-31 19:37
What I think is happening is the gamepad isn't mapped correctly in Chrome.  The most feasible solution for this is gamepad mapping (#30), which doesn't exist at this time.  If you're up for it, you could investigate mapping your controller in the Chromium source, but I can't offer any assistance with that.
