### ISSUE TITLE
Mouse Issue, pulls back to center during use

### ISSUE THREAD

**Issue by aguyinag** [moonlight-stream/moonlight-chrome#376] opened 2017-12-20 08:02 UTC
Hi,

I'm having this issue where everything seems to be working properly, except for the mouse. This is my first time using Moonlight as a disclaimer, so I'm not sure if there's something I did wrong. Whenever I launch a game from Moonlight, it opens correctly but the mouse constantly pulls back as if it were rubberbanding back to a previous position. This happens no matter which direction I move the mouse, it moves maybe 1/3-1/2 of the screen and will instantly move back to the "center". I say center with quotation because occasionally, when I move the mouse fast enough or something, the center will change to a different position, generally in the direction I've been moving the mouse. It will then start pulling back to that new center, with similar allowance for movement before it does. This will also happen in first person games where the cursor disappears and the mouse is used to look around. If I look too far from a certain position, the game POV will pull back exactly like the mouse movement on the desktop. I can provide more information about the computer, setup, or anything if is needed.

**Comment by cgutman** [comment] 2017-12-20 08:24
Duplicate of #353

There is a workaround in that ticket. It will be fixed in Chrome 64.

**Closed by cgutman** 2017-12-20 08:24 UTC
