### ISSUE TITLE
Black screen with audio

### ISSUE THREAD

**Issue by Sacred18** [moonlight-stream/moonlight-chrome#106] opened 2016-09-08 15:09 UTC
So i'm having the problem where i have a success connection and then got a black screen with only the audio of the game in the back.
I've tried searching for this in online forums and nothing.

Im trying to stream from a windows machine to another (windows  10)

Specs:
Core i5 4460
GtX 970

**Comment by raidancampbell** [comment] 2016-09-08 15:47
Duplicate of #105

**Closed by raidancampbell** 2016-09-08 15:47 UTC
