### ISSUE TITLE
Moonlight muted the audio while inactive

### ISSUE THREAD

**Issue by evildog1** [moonlight-stream/moonlight-chrome#165] opened 2016-12-31 17:41 UTC
When i pause the game or pause the video for a minute and sometime just 15 seconds without any audio playing in the background, Moonlight automatically muted the audio until i quit the stream but the audio icon is still on. I'm using my laptop to stream my gaming PC through local ethernet. I reproduced this bug on my mom's mini notebook running Win 10 x86 and it happens too, so i can confirm that the bug is from Moonlight..

The simple solution was to play a silent mp3 file and let it looping to prevent the audio being muted

My gaming PC is running Windows 10 x64.  All drivers are updated
My old laptop is running Windows 7 x64 with Chrome 55.0.2883.87 (64-bit).  All drivers are updated

This bug is not happen on Android and iOS version of Moonlight

Do you know how can i collect logs of moonlight?

**Comment by xchannels** [comment] 2017-01-02 20:26
I have the same problem. It mutes quickly when there are no audio activity, not your activity.

**Comment by ShadowBullet** [comment] 2017-01-03 15:08
@cgutman @raidancampbell having this same issue as well... Think it is just this version of moonlight, never happened in other versions.

**Comment by xchannels** [comment] 2017-01-03 18:42
Evildog1 i see that you made the simple tool that fixes Fullscreen on Chrome for moonlight. Can you make a tool that is running silent audio to prevent auto mute?

**Comment by evildog1** [comment] 2017-01-05 08:06
@xchannels that's the good idea. I'm working with it and test before release

**Comment by evildog1** [comment] 2017-01-05 20:13
Forgot to run media player. Audio always mute while i'm inactive. I quit and connect again and i got this wierd bug

![image](https://cloud.githubusercontent.com/assets/8687585/21695850/bb0b899a-d38b-11e6-9722-7308cef44b4b.png)

**Comment by juskdtlm** [comment] 2017-01-09 08:47
I'm having the same issue and i can confirm it's not happening on Android

**Comment by evildog1** [comment] 2017-01-11 13:53
Ok, temporary solution: Here is my small program that loops very silent wav audio to keep audio active and to prevent Moonlight muting the audio while idle. Open it on your gaming PC, not on client PC. I'm testing it out
https://drive.google.com/open?id=0B_6TXpxCnMc7ZHFSeXdHZnVaVGs

Note: 360 anti-virus give false positive

**Comment by ShadowBullet** [comment] 2017-01-11 15:12
Just downloaded it, will let you know how it works

**Comment by evildog1** [comment] 2017-01-11 16:30
Forgot to mention, to stop the program, Right click on icon tray and select Quit.
To know if it is working, open Audio mixer and the program Audio Fixer should appear as a volume

**Comment by xchannels** [comment] 2017-01-20 16:24
Thank you so much for the program!

**Comment by raidancampbell** [comment] 2017-02-24 21:55
Unable to reproduce:
Server: Win10 x64, GFE: 3.1.2.31
Client: OSX, chrome 56.0.2924.87 stable

If someone is still having this problem, let me know and I'll cook up a windows client to try and replicate.

**Comment by xchannels** [comment] 2017-02-25 17:42
I'm also unable to reproduce on Android and iOS, so i guess Windows only have this issue due to power saving, but i have disable everything related to power saving. I don't have OSX system. I'm still using Evildog1's Audio Fixer for temp. solution.
I can try to reproduce this bug on Win7 and Win10 client again and report.

**Comment by evildog1** [comment] 2017-02-26 17:05
@raidancampbell i can reproduce this issue. can you tell me how to collect logs of Moonlight?

**Comment by raidancampbell** [comment] 2017-02-26 18:20
@evildog1 You're welcome to give it a shot by following the instructions [here](https://github.com/moonlight-stream/moonlight-chrome/wiki/Home#reading-the-chrome-app-logs), but I honestly don't expect anything useful.  I'm thinking there's either a Chrome bug or an updated API that needs different permissions.

**Comment by evildog1** [comment] 2017-02-28 11:42
@raidancampbell i reproduced it twice but it seems the bug has been fixed. Close this issue for now

**Comment by raidancampbell** [comment] 2017-02-28 18:11
Closing, unable to reliably reproduce

**Closed by raidancampbell** 2017-02-28 18:11 UTC
