### ISSUE TITLE
Mouse stuck in box and unplayable in full screen and windowed please help

### ISSUE THREAD

**Issue by SlayerUSA** [moonlight-stream/moonlight-chrome#335] opened 2017-10-10 13:10 UTC
Mouse stuck in box and unplayable in full screen and windowed, same with wireless mouse too.

https://www.youtube.com/watch?v=d8ID01ToY3k
https://www.youtube.com/watch?v=0UlcwNjEjmE

Any ideas on how to fix this? thanks in advance

**Comment by MagFlux** [comment] 2017-10-15 14:31
Hey @SlayerUSA, I have this same issue.

I asked about this around a week or so ago in issue #324. Looks like the one guy who was nice enough to respond doesn't know. He believed it to be a hardware issue but at this point based on my experiences and yours I don't believe that to be the case.

I haven't found the time (and honestly may never) but I'm hoping to look into this and see if I can resolve it.

**Comment by SlayerUSA** [comment] 2017-10-15 14:36
Thanks for commenting, I hope this issue is resolved soon. I don't know what else to do to try to fix this and its very frustrating as it was working fine before it happened. Still not working though

**Comment by MagFlux** [comment] 2017-10-15 14:43
Hmm interesting, this worked before for you on that same laptop/OS combination? I'm wondering if this was a recent regression then. I have only had this issue for a couple of months (if I recall correctly) but mind you its always been an issue on my Pixel running ChromeOS and has never worked right.

Not sure if you read through my issue but using the Pixel running Ubuntu resolves the problem so to me it seems to be some type of Chrome OS issue or at least an inconsistency with however the Moonlight extension gets/sets mouse positions through the OS.

**Comment by SlayerUSA** [comment] 2017-10-16 04:45
I think you may be right. If it helps, my iPhone moonlight app works fine, although could never get that to work over the internet. I tested the previous moonlight version and it was still messed up. I think its the chrome OS update, but i'm using a school Chromebook so I cant rollback the version I think. I tried to with the alt Ctrl shift and r but nothing pops up. I guess I will have to wait for the next moonlight version to solve this. I have to use chrome remote desktop app on my phone to move the mouse, good thing GTA 5 doesn't need a mouse 100% to play.

**Comment by SlayerUSA** [comment] 2017-10-19 14:55
and the chrome remote desktop on chromebook to pc works fine so I think its just moonlight's software

**Comment by SESNut** [comment] 2017-10-20 03:53
i have this problem too. It has something to do with the version of chrome youre using. Before it would only jump around if I was dragging something, but then i restarted chrome and now this. I had the dev branch installed before and had the same problem before i installed the release version of chrome, but its probably caught up to the dev branch now. I dont know what the fix is. I had to start using the java version just to get reliable mouse movement

**Comment by SlayerUSA** [comment] 2017-10-20 12:52
Not sure what to do myself besides to wait for moonlight to be updated, **does anyone know an admin or something?** its a shame this mouse issue came up moonlight is so awesome and works perfect besides that issue, it was working fine too until chrome got updated.

**Comment by airdjing** [comment] 2017-10-21 12:07
I have same problem from yesterday

**Comment by MagFlux** [comment] 2017-10-21 13:58
@Jorys-Paulin, @jacobmix, sorry to tag you two directly but this problem definitely seems to be more than an outlier now. Either of you have any ideas?

Thanks in advance!

**Comment by Jorys-Paulin** [comment] 2017-10-21 14:46
Looks like lag compensation to me. I don't know if thats a thing they implemented, but thats what it looks at first sight. What is the connection between the two PCs?

**Comment by Jorys-Paulin** [comment] 2017-10-21 14:52
One thing that could help though: does it also append when you're on moonlight's menus?

**Comment by airdjing** [comment] 2017-10-21 15:25
In my case, there was no problem until the day before yesterday. This problem suddenly appeared.
I'm using 802.11ac wireless on client, Gigabit on server
This is a comparison of LOCAL, VNC and MOONLIGHT.

https://youtu.be/pnQEUvYuyZ8

Maybe could it be a problem caused by WINDOWS 10 RS3 (1709) UPDATE?

**Comment by Jorys-Paulin** [comment] 2017-10-21 15:54
@airdjing I just noticed you don't have the "Allow optimisations" icon introduced recently. Make sure you update, just in case. Otherways, How does it looks from the host's screen? I seriously think it's something like input lag, but I'm not sure.

**Comment by airdjing** [comment] 2017-10-21 16:13
I only use remote windows to Moonlight (not gaming)
GameSteam desktop (mstsc) has No optimisation options on GFE
Host screen's mouse moving is same my YouTube example on moonlight connected

I don't think this problem reason for the optimisations or network bandwidth
Because there was no problem until before yesterday. This problem suddenly appeared.

This is my version setting
Gamestream client : Windows 10 x64 1709.16299, Windows Chrome 62.0.3202.62, Moonlight 0.74
Gamestream server : Windows 10 x64 1709.16299, GF Driver 387.92, GFE 3.10.0.95

**Comment by Jorys-Paulin** [comment] 2017-10-21 19:10
@airdjing I meant directly linking the two computers to get rid of any network influence.

**Comment by airdjing** [comment] 2017-10-22 08:39
I tried direct lan cable link, changing lan cable, Reinstall OS, use another client (another windows pc)
It's the same thing that I try to do.

**Comment by SlayerUSA** [comment] 2017-10-22 17:50
Its definitely a mouse problem because game streaming works very very well even over the internet, not on same network, and definitely a chrome update causing this, because im on same windows and same moonlight versions before and after this happened.  I have no idea how to fix it though

**Comment by airdjing** [comment] 2017-10-23 00:45
Guys, Maybe I have found a problem reason.
I think this problem with the 1709 version of Windows 10 and moonlight client.
Previous versions of 1703 do not have problems.
They were filmed on the same network.

https://youtu.be/PSSomRPvkkU - 1703, No Problem
https://youtu.be/YKtl0H_S8hY - 1709, Problem

@SlayerUSA, Isn't your window 10 version is 1709 too? Plz check your winver
(Mean Windows 10 Fall creators update)

**Comment by SlayerUSA** [comment] 2017-10-23 01:23
version 1607, Im using chrome os moonlight to stream to windows pc 1607

**Comment by airdjing** [comment] 2017-10-23 08:05
@SESNut What's your client settings and version?
@SlayerUSA I think server's windows version does not seem to be related. Need to find out what your client and my client have in common. When did you start having problems? and what are the specific program setup states and versions?

**Comment by airdjing** [comment] 2017-10-23 11:40
Old java client (moonlight pc win64.jar 0.75) is no problem.
Problem only appears Chrome version... very weird.
https://youtu.be/qsJx1MCfYvU

**Comment by SlayerUSA** [comment] 2017-10-24 00:53
I started a few days before I posted this so like 17 days ago, before then it worked fine
Moonlight Chrome v0.7.4
windows 10 ver 1607, (I didnt like the creators update, so I downgraded a long time ago)
chrome os version 61.0.3163.120 (Official Build) (64-bit)

**Comment by nihique** [comment] 2017-10-24 06:46
I also have exact same problem. Running Chrome 62 and Win10 1709 Falls Creator Update.... It was working before. Not sure if this is Chrome problem or Win problem....

**Comment by johnblaze00** [comment] 2017-10-24 22:16
I am also having the same issue, Version 63.0.3239.9 chrome. Client is windows 10 fall creators update, host is just the creators update with Chrome version 62. This is over the same network on a wired connection, tried on a laptop over wireless AC as well, same issue.

**Comment by jliang14** [comment] 2017-10-25 17:42
Same problem here. Was working fine, then updated to 1709 and seeing the exact same mouse skipping. I may rollback my version of Windows until it's fixed.

**Comment by johnblaze00** [comment] 2017-10-26 16:21
Tried playing/streaming to my macbook air and had no issues, but be a fall creators update issue. the host isn't running it.

**Comment by Zibbibbo** [comment] 2017-10-27 21:44
I think the problem is localized to the CLIENT side.

I have recently upgraded my home's pc and installed latest windows 10 build 1709

At work i have many pcs, this mouse issue is present only on pc with the 1709 build and works perfectly with 1703 build.

So the problem is not on the host pc, but on the client.

**Comment by SlayerUSA** [comment] 2017-10-28 00:06
Im on 1607 damn, I might update then, thanks

**Comment by airdjing** [comment] 2017-10-30 10:35
Several many tests have been confirmed of certainty.
When the client is Windows 10 Fall creators updated (1709), there is a problem.
Can this be improved?

**Comment by SlayerUSA** [comment] 2017-11-02 13:42
got it working on 1703 thanks

**Comment by MagFlux** [comment] 2017-11-04 15:24
@SlayerUSA, so upgrading the server (aka Windows) resolved the problem for you when using your ChromeOS client? Hmm, so to summarize: 1607 doesn't work, 1703 does, and 1709 doesn't? But again I find this odd because for me 1709 only doesn't work when using the Chrome extension via ChromeOS, connecting to a 1709 server via Ubuntu using the Chrome extension works just fine.

**Comment by Jorys-Paulin** [comment] 2017-11-04 15:34
@MagFlux That would mean the chrome version might be the factor here

**Comment by SlayerUSA** [comment] 2017-11-04 15:50
I got Microsoft support to update my pc to 1703 and it works now so it was the windows update causing the problem. I had to make a new thread though because it keeps disconnecting when im using it over the internet.

**Comment by cgutman** [comment] 2018-01-24 22:56
Closing per #353

**Closed by cgutman** 2018-01-24 22:56 UTC

**Comment by Haikv** [comment] 2018-04-10 09:37
After updating to 1709 mouse bug happens in many games, also in winrar drag and drop or just desktop icons moving.
