### ISSUE TITLE
Mouse glitch on Windows 10 RS3 (version 1709 Fall creators update)

### ISSUE THREAD

**Issue by airdjing** [moonlight-stream/moonlight-chrome#353] opened 2017-11-03 03:07 UTC
This situation causes a mouse glitch when running moonlight-chrome on newly released Windows 10 1709 (RS3, Fall creators update)

I tested various situations in my own way.
It occurs when only client OS is Windows 10 1709.
And the rest does not matter whether it is a client any chrome version and server's any GFE version.

Example videos
- Problem
https://youtu.be/Ei5wEsJv3lY (Wireless Network, Win 10 1709)
https://youtu.be/YKtl0H_S8hY (Wired, Win 10 1709)

- No Problem on Win10 RS2 (Wired, Win 10 1703)
https://youtu.be/PSSomRPvkkU

- LOCAL CLIENT vs VNC vs MOONLIGHT (Wireless Network, Win 10 1709)
https://youtu.be/pnQEUvYuyZ8

- No Problem on Android (Wireless)
https://youtu.be/hnCkmvd79sE

Is the solution only a rollback to 1703?

**Comment by nhtones** [comment] 2017-11-03 21:29
Also seeing similar behaviour - latest moonlight chrome extension.

**Comment by MagFlux** [comment] 2017-11-04 15:28
This looks to be the same issue as seen in issues #335 and #324. Tagging them here for reference.

**Comment by airdjing** [comment] 2017-11-04 16:04
@MagFlux 
I think this is not a physical problem with a mouse input or a network.
Because I tested only change OS on the same PC, same network connection, same input controls
then result is different.
and same client's chrome version, same server's GFE version and same server's geforce driver version too.

**Comment by johnblaze00** [comment] 2017-11-04 16:22
no its a problem if the client is on 1709, 1703 works fine, other OS work fine. I have been gaming with my macbook pro lately as its basically unplayable on my windows 1709 desktop and it wont let me revert back for some dumb reason even though i didnt remove the previous install or delete the "windows.old" folder... got to wait for these guys to upgrade before I can play this again.

**Comment by defcon1186** [comment] 2017-11-08 14:39
Same issue here, and yes, I'm on 1709 version recently updated...  #358

**Comment by llajas** [comment] 2017-11-10 13:56
I am also experiencing this exact issue. Just like the video, it's only apparent I try and move my mouse while simultaneously holding/pressing a button on the mouse itself. i.e.: Holding right mouse to aim down the sights/scope in an FPS while looking around, or just simply holding left mouse to auto-fire is next to impossible if I try and look around at the exact same time.


Both client & server are on the new Fall Creators Update (Build 1709) of Windows 10. I currently don't have the ability to roll back from 1709 easily, but the issue wasn't present when using a friends computer running Windows 7, so it's definitely something isolated to Windows 10 v1709, from my testing.

**Comment by cgutman** [comment] 2017-11-13 07:02
Here is a build with a workaround. It's not perfect, but it ignores most of the errant mouse events. I don't feel comfortable rolling the fix out in the official build, because it can accidentally mark valid movements as errant and create problems where there were none before. https://drive.google.com/open?id=1NhdQ2AFss1Y8RRXbal9HDSjnAwO_90hO

I filed a bug on Chrome for investigation as this bug affects all users of Pointer Lock, not just Moonlight. Feel free to star the bug, but don't comment unless you have some technical analysis to add (since it sends everyone on the ticket an email). https://bugs.chromium.org/p/chromium/issues/detail?id=784122

**Comment by airdjing** [comment] 2017-11-14 01:47
@cgutman 0.75(rs3hack) version you provided works pretty well. I'll use this until chrome's bugs get fixed. 
Moonlight is an important application in my life.
I highly appreciate for your hard work. Thank you.

**Comment by MagFlux** [comment] 2017-11-14 02:40
@cgutman Thanks for putting out this hotfix! Solves the problem I was seeing, working quite well. Thanks again for taking the time to look into this and determine a root cause.

**Comment by llajas** [comment] 2017-11-14 06:28
@cgutman Thanks for the quick patch! It feels like there is a slight delay when compared to running the official release on a Pre-Creators update box, but it is much better now than where it was at first.

**Comment by nebiont** [comment] 2017-11-14 20:46
@cgutman Thank you so much for the custom build, it's working perfectly! Hopefully a fix is implemented into Chrome soon.

**Comment by nicholson101** [comment] 2017-11-20 10:29
Hotfix isn't working for me. Still getting the mouse jumps :-(

**Comment by ConnorTheFox** [comment] 2017-11-26 08:56
@cgutman Thank you so much. At times there are still jumps, but for the most part, it working great.

**Comment by airdjing** [comment] 2017-12-07 09:42
Today chrome Updated to 63.0.3239.84 version.
But problem still exists.

**Comment by srimshady** [comment] 2017-12-12 06:05
@cgutman Can I ask how you went about fixing this bug? I have a web gl fps game that is having trouble in chrome. I am really stuck on what to do.

**Comment by cgutman** [comment] 2017-12-12 06:17
@srimshady I'm using heuristics that look for a large mouse movement in the opposite direction of the current movement direction.

The change is here: https://github.com/moonlight-stream/moonlight-chrome/commit/3c6a63c56847a7b462f13a55f8138dd92a725c7f

**Comment by srimshady** [comment] 2017-12-12 06:36
@cgutman thanks for responding so fast. I'm not sure how to get that low level access in JavaScript but I'll try haha.

**Comment by airdjing** [comment] 2017-12-18 02:33
That's good news.
Chrome updated to 63.0.3239.108
In my case Problem is gone. See if it works well check it out

**Comment by airdjing** [comment] 2017-12-18 02:38
Now chrome Updated to 63.0.3239.108 version.
Sadly, problem still exists.

**Comment by cgutman** [comment] 2017-12-21 21:48
The bug is fixed in Chrome Beta (64.0.3282.39)

**Comment by Jorys-Paulin** [comment] 2017-12-26 14:04
@airdjing I guess you can close this issue now :)

**Comment by cgutman** [comment] 2018-01-24 22:54
Chrome 64 has reached stable today. Closing this issue.

**Closed by cgutman** 2018-01-24 22:54 UTC

**Comment by Haikv** [comment] 2018-04-10 09:33
I have the same issue after updating or clean installing 1709. Drag and drop not working, also mouse glitch in many games when moving. This issue only with 1709 version. v1703 works fine.
