### ISSUE TITLE
Interface improvements

### ISSUE THREAD

**Issue by igrik1986** [moonlight-stream/moonlight-chrome#67] opened 2016-06-28 12:38 UTC
Hello,

Would be really great to make it look more like Android versions. The same goes to Java PC version.

I would also recommend introduce automatic quit from the app itself when pressing Ctrl+Shit+Alt+Q.

Otherwise kids might forget to quit a game, and it heavily consumes power from the PC.

Thank you

**Comment by raidancampbell** [comment] 2016-06-28 13:18
Duplicate of #34, which is already in progress on Master.  

Ctrl+Shit+Alt+Q currently has expected behavior: quit the stream, but leave the app running.  This way we can quickly resume it later.  The thought process behind this was to protect unsaved progress: otherwise there is no way to quit the stream without quitting the app.  In my opinion, losing unsaved progress has a higher penalty than leaving an app running on the computer.

Thank you for your comment, and please let me know if you disagree.

**Closed by raidancampbell** 2016-06-28 13:18 UTC

**Comment by igrik1986** [comment] 2016-06-28 21:22
I have experience when program remains running when you stop streaming and close plugin. I still think it should be at least configurable.
