### ISSUE TITLE
Since most recent GeForce Experience update certain buttons not working

### ISSUE THREAD

**Issue by nicholson101** [moonlight-stream/moonlight-chrome#223] opened 2017-04-12 12:12 UTC
Since I've updated to 3.5.0.70 I'm unable to use ctrl, shift and Alt in games. All other keys seem to be working fine. I've reinstalled both moonlight and GF experience to no success and also tried a different keyboard.

**Comment by cemarriott** [comment] 2017-04-12 12:34
Having the same issue. I find that if I repeatedly hit one of those keys that it will eventually fire. However the keys can't be sustained, they fire once quickly as though they were pressed and released, even if you are holding the key down.

**Comment by nicholson101** [comment] 2017-04-12 12:37
Exactly this! Playing Just Cause 3 when trying to start up the helicopters engine, if i repeatedly press shift (rotors) the rotors spin for a second and then stop.

**Comment by jimb0616** [comment] 2017-04-12 22:20
I'm having the same exact issue and it's happening with my "shift" key, and a few others. Such a pain!!

**Comment by jimb0616** [comment] 2017-04-13 12:38
It seems the keys that are used to close the stream (ctrl+alt+shift+Q) are the ones not working right. Well, Q works fine but not the others. And it's only in-game they don't work. When streaming the desktop or chatting in game they work fine.

**Comment by Banana-In-Black** [comment] 2017-04-15 07:23
Yes, I have the exactly the same issue. You can't long press alt / ctrl / shift.

**Comment by WidgetPhreak** [comment] 2017-04-17 01:26
It would appear that what is happening, since the latest nVidia update, is that now the CTRL, ALT, and SHIFT keys are registering a "Held Keypress" as a "Rapid Fire".
Example:
In Overwatch... as Soldier 76... you Hold LEFT_SHIFT to Sprint.  You Hold CTRL to Crouch/Duck.
After the Recent update... Holding LEFT_SHIFT while walking causes the Sprint to go ON/Off/ON/Off/On/OFF. If you hold CTRL to Crouch... you basically end up "Tea-Bagging" (crouch crouch crouch crouch crouch).

In GTA Online... Holding Shift is Also  a Sprint... Same thing Happens.  CTRL lets you do Wheelies on Motorcycles... and it lets you Tilt Helicopters.  But with the Current Bug... it's basically impossible to control a Helicopter... a riding a Motorcycle is problematic... because you need wheelies so the Bike and launch over Rocks/Onstacles... rather can crashing.

**Comment by airdjing** [comment] 2017-04-17 12:17
Same issues here

**Comment by nicholson101** [comment] 2017-04-18 06:46
I feel this has rendered the current version unusable for now as almost all games require shift/ctrl/alt. The only way would be to roll back Geforce experience to the previous version and prevent it from updating for the time being.

**Comment by ShadowBullet** [comment] 2017-04-18 13:22
Okay everyone, I have compiled a version of Moonlight that it current with all current Commits, I found that Game Box Artwork works again so that is a good thing, let me know if this possibly fixes any of the issues described in this thread. I have posted a link to the compiled version down below, just follow the standard install instructions as in previous releases. 

https://drive.google.com/open?id=0B4igNzfYt4TzMkZMMHFTLXBpdzg

**Comment by WidgetPhreak** [comment] 2017-04-18 16:08
I know the official stance on this is probably "we don't support it any more", but...
Any chance of getting an updated version of the .jar [java based] client?

I've found it to be consistently more reliable than the Chrome Version when I stream from my Home network to my Laptop at work.  [example... on the Chrome Version... if I disconnect... I can't reconnect again until I reboot the Windows PC... but with the Java version... I can disconnect/reconnect as much as I want... 

I've even found that If the Chrome Version won't connect... the Java version will... and by connecting with the Java Version... and then Disconnecting... the Chrome Version will connect again].

**Comment by WidgetPhreak** [comment] 2017-04-18 17:08
I can confirm... the new .crx posted above still exhibits the same issues with CTRL, ALT, and SHIFT.
I've uploaded a video example of what's going on... on the off chance it will help the developers.
<iframe width="560" height="315" src="https://www.youtube.com/embed/wQA5SDQsGL4" frameborder="0" allowfullscreen></iframe>

**Comment by xxblindmonkeyxx** [comment] 2017-04-18 18:06
I have rollee back to 3.3 and the issue persists??

**Comment by xxblindmonkeyxx** [comment] 2017-04-18 20:41
My fault it had auto updated again. How do you stop that?

**Comment by nicholson101** [comment] 2017-04-18 20:45
I think I've figured that part out as it auto updated on me too. In "program data/Nvidia corporation/downloader" i renamed setup to something random. I haven't fully tested this yet but i believe this works. Make sure you do this as soon as you have installed the desired version.

**Comment by WidgetPhreak** [comment] 2017-04-18 20:46
No such luck for me.
I manually removed everything nvidia related from my machine via add/remove
programs...  and tried several different old versions of the drivers and
the nvidia experience...
I even went as far back as using the April 2016 drivers from the CDROM that
shipped with my GFX card... and told them not to auto update.
Problem persists.
-- 
Andrew Yamane | Lead Technician
(602) 8 Bit MAN  | (602) 824 8626

**Comment by nicholson101** [comment] 2017-04-18 20:48
So the key presses aren't registering with any version for you!?

**Comment by WidgetPhreak** [comment] 2017-04-18 20:51
They've always registered.
The problem is... that since the update (and attempted rollbacks) CTRL ALT
& SHIFT "Rapid Fire" when Held, rather then just registering a Long
Press/Press and Hold.
-- 
Andrew Yamane | Lead Technician
(602) 8 Bit MAN  | (602) 824 8626

**Comment by nicholson101** [comment] 2017-04-18 20:57
That's a new one on me!? I'm getting no button recognition on ctrl/shift/alt at all. Long or rapid press. Hi

**Comment by jimb0616** [comment] 2017-04-18 21:11
I'm shocked that the dev of moonlight-streaming hasn't published an update
since the last one. I'm hoping this can be resolved without having to
rollback nVidia drivers. For now, I'm using CAPSLOCK as my sprint and
steady scope buttons, in place of shift.

**Comment by jimb0616** [comment] 2017-04-18 21:14
Though it's related to the nVidia GFE update, the dev has usually been on top of fixes and publishing updates... especially for big issues like this one.

**Comment by nicholson101** [comment] 2017-04-19 07:05
my above fix for stopping geforce experience from updating has not worked. My only option at the moment is to remote in to my PC via teamviewer and uninstall the most recent version and then install the previous version making sure the window stays open (preventing it from updating) on first open....

Every. Single. Time..... :-(

**Comment by ShadowBullet** [comment] 2017-04-19 13:12
Okay, if anyone knows how to code at all lines 37-52 in the input.cpp file seems to be were it takes in the input of the SHIFT, CTRL, ALT keys. If we can change that and possibly make our own branch of the project then maybe we might be able to fix it. @raidancampbell @cgutman @dead Still holding out hope that possibly one of you guys might be able to assist us. 

For those wondering here is the link to the input.cpp file https://github.com/moonlight-stream/moonlight-chrome/blob/master/input.cpp

And here is line 32-57 just in case you don't want to go to the link

static char GetModifierFlags(const pp::InputEvent& event) {
    uint32_t modifiers = event.GetModifiers();
    char flags = 0;
    
    if (modifiers & PP_INPUTEVENT_MODIFIER_SHIFTKEY) {
        flags |= MODIFIER_SHIFT;
    }
    if (modifiers & PP_INPUTEVENT_MODIFIER_CONTROLKEY) {
        flags |= MODIFIER_CTRL;
    }
    if (modifiers & PP_INPUTEVENT_MODIFIER_ALTKEY) {
        flags |= MODIFIER_ALT;
    }
    
    return flags;
}

**Comment by ShadowBullet** [comment] 2017-04-19 13:50
Okay everyone I have good news and bad news, the good news is issue is most likely not with Moonlight (WOOHOO!) The issues is possibly with GFE itself, check forum here https://forums.geforce.com/default/topic/1000847/gamestream/everything-was-fine-yesterday-now-ctrl-shift-alt-no-longer-works-when-gamestreaming/

**Comment by ShadowBullet** [comment] 2017-04-19 13:52
Possibly may still have to update Moonlight however just saw that they updated Shield Hub and they said they pushed an update to that that may have fixed it, so we may still need an updated version of Moonlight. @cgutman @raidancampbell @dead PLEASE HELP US YOUR OUR ONLY HOPE

**Comment by WidgetPhreak** [comment] 2017-04-20 02:41
If the GFE update broke nVidia's Official Shield software too, and their
fix involved an update to the Shield, and not the GFE... Moonlight will
require an update for sure.  If they had opted for an additional update to
the GFE to resolve the issue... we could have waited for that.  But it
looks like nVidia has done all they are gonna do (patch their official
Shield Devices).  Since our Shield solution is Moonlight... the devs or
community will have to provide our solution.
-- 
Andrew Yamane | Lead Technician
(602) 8 Bit MAN  | (602) 824 8626

**Comment by cgutman** [comment] 2017-04-20 03:48
I'm aware of the issue and have tried several ways to workaround it, but without much luck.

As far as I'm concerned, the jury is still out on whether this is a GFE or Moonlight/Shield issue. My Shield has no option to update to the version mentioned in that forum thread, so Shield folks are dead in the water too.

APKMirror also has no record of the build they're saying will fix the issue: https://www.apkmirror.com/apk/nvidia/nvidia-games/

That's not to say it's not out there, but they've at least botched the deployment of it somehow. Without being able to peek at what Shield Hub is doing, this won't get fixed soon.

**Comment by ShadowBullet** [comment] 2017-04-20 03:54
Well at least it is on both platforms then, hopefully NVIDIA will issue a hotfix through GFE and fix it for everyone. Also @cgutman any chance that once this is resolved perhaps if you are willing to/have time for it, would you consider updating the project a little bit more? I know it is still in an alpha state, and since chrome apps are going out the wayside perhaps we need to come up with a permanent solution for Moonlight on the PC. Any ideas on what such development might transpire from this? Also thank you very much for weighing in on this issue. I know that it means a lot to us when you respond to inquiries and bugs such as this thread and I think I speak for everyone when I say that.

**Comment by cgutman** [comment] 2017-04-20 04:23
At this point, I'm not sure what the future of Moonlight on the PC will be. We tried to kill Java and replace it with Chrome to reduce our support work, but now we really just have twice the PC clients with different quirks to maintain.

The best path forward is probably (yet another) rewrite but this time in C++ with Qt. We can be pretty sure that's not going away any time soon ;)

**Comment by nicholson101** [comment] 2017-04-20 10:00
It would be a shame to leave the PC client of the list of options. I have a shield portable and a shield TV but still use the PC client the most!

**Comment by k7000i** [comment] 2017-04-20 11:42
Latest apk here (2017.04.06) https://apkpure.com/store/apps/details?id=com.nvidia.tegrazone3

**Comment by TheNferno** [comment] 2017-04-21 15:36
In regards to cgutmans response about the future of Moonlight, I really like the chrome client as it allows me to use my chrome book as well as use Moonlight on computers where I do not have admin access. I understand the longevity that comes with the C++ rewrite but I really like the functionality of the chrome client. 
BTW, all I know to write in is HTML and really basic Flash so please educate me if make wrong assumptions

**Comment by ApexAftermath** [comment] 2017-04-22 22:02
Same issue here. I hope nvidia fixes the issue on their end as it seem the problem comes from GFE.

**Comment by ShadowBullet** [comment] 2017-04-24 02:15
Okay guys, 13 hours ago (at the time of writing this) a mod over at the NVIDIA forums commented again on that forum I had posted a bit ago. (link in case you forgot: https://forums.geforce.com/default/topic/1000847/gamestream/everything-was-fine-yesterday-now-ctrl-shift-alt-no-longer-works-when-gamestreaming/) Hopefully once the update drops we cna get a patch fix for Moonlight so it can go back to a working state.

**Comment by minnux** [comment] 2017-04-28 19:19
Just commenting to see if there's any kind of time table yet for an update to this problem. Or is this solely contingent on Nvidia pushing a new update for GFE and we're just waiting on them?

**Comment by cgutman** [comment] 2017-04-28 19:23
We need either a GFE update to fix the issue or a Shield Hub update to see how they fix it.

**Comment by minnux** [comment] 2017-04-28 19:25
Thanks for the quick reply. I will go check with Nvidia and see if there's any update time table.

**Comment by jimb0616** [comment] 2017-04-28 19:28
Can't we just extract the code from their latest update and configure it
then input to MLS?

**Comment by cgutman** [comment] 2017-04-29 00:43
That's much easier said than done.

**Comment by jimb0616** [comment] 2017-04-29 01:43
I realize that,  but it is possible.  I wish I had the time to do it myself
but I don't.

**Comment by nicholson101** [comment] 2017-05-02 05:59
If it will tip Nvidia's hand, can we all keep the above thread alive on the geforce forums so that they take notice?

**Comment by cgutman** [comment] 2017-05-04 16:26
This is fixed in GFE Beta 3.6.0.74.

Open GFE, go to settings, and check the "Allow experimental features" box. Give it a couple minutes to download in the background, then restart GFE and it should prompt you for the update.

**Closed by cgutman** 2017-05-04 16:26 UTC

**Comment by jimb0616** [comment] 2017-05-04 21:11
Thanks for the info!

**Comment by Ononeemas** [comment] 2019-08-06 22:50
Same issue. I've set caps lock on "toggle mute" option in geforce expirience in-game overlay and then caps lock stopped working at all, only indicator lightning at keyboard continued to switch w/o any effect. It took 30mins to realize what's wrong.
