### ISSUE TITLE
Audio on Host PC?

### ISSUE THREAD

**Issue by Shadowfita** [moonlight-stream/moonlight-chrome#85] opened 2016-08-05 11:03 UTC
Hi, I was wondering if there were any tricks to getting Audio on the Host PC with the current release of this particular branch because it seems to run a lot faster than the java release.

Thanks.

**Comment by raidancampbell** [comment] 2016-08-05 15:45
duplicate of #83 and #60.  The link for a preview build can be found in those issues.

This feature is getting requested often enough that I'm going to leave this issue open until the next release.

**Comment by Shadowfita** [comment] 2016-08-05 21:24
Thank you.

**Comment by MisterCreative** [comment] 2016-08-12 21:01
I would really like for there to be sound as well. I can only agree that the chrome extension is a thousand times better than the java one. @raidancampbell I tried your newer build but it still didn't play the audio on the host pc even with the setting turned on or off. Otherwise great work! :D

**Comment by raidancampbell** [comment] 2016-08-12 22:06
I'm unable to help you, unfortunately: I haven't had local access to a GFE computer for several months.  It seems that the test build worked for other people, so I can only suggest the usual battery of retrying, rebooting, and updating.

**Comment by raidancampbell** [comment] 2016-09-03 16:38
Closed, alpha 5 has this built in, so there's no longer a reason to keep links to the super unofficial dropbox builds around.

**Closed by raidancampbell** 2016-09-03 16:38 UTC
